# action.yml
name: 'Sauce Connect Proxy Action'
description: 'A GitHub action to launch Sauce Connect Proxy'
author: Christian Bromann
branding:
    icon: server
    color: red
inputs:
    username:
        description: Sauce Labs user name.
        required: true
    accessKey:
        description: Sauce Labs API Key.
        required: true
    cacertFile:
        description: CA certificate bundle to use for verifying REST connections.
        required: false
    configFile:
        description: Path to YAML config file. Please refer to https://docs.saucelabs.com/secure-connections/sauce-connect/setup-configuration/yaml-config/.
        required: false
    directDomains:
        description: Comma-separated list of domains that you want to relay directly through the internet instead of through the Sauce Connect Proxy tunnel.
        required: false
    dns:
        description: 'Use specified name server. To specify multiple servers, separate them with comma. Use IP addresses, optionally with a port number, the two separated by a colon. Example: --dns 8.8.8.8,8.8.4.4:53'
        required: false
    denyDomains:
        description: Comma-separated list of domains that you want to deny access through the tunnel.
        required: false
    apiAddress:
        description: Host:port for the status server used to expose client metrics.
        required: false
        default: 0.0.0.0:8080
    statusAddress:
        description: Host:port for the status server used to expose client status.
        required: false
    tunnelPool:
        description: Denotes a tunnel as part of a high availability tunnel pool.
        required: false
    tlsPassthroughDomains:
        description: Comma-separated list of domains. Requests whose host matches one of these will not be SSL re-encrypted.
        required: false
    pac:
        description: Proxy autoconfiguration. Can be an http(s) or local file:// (absolute path only) URI.
        required: false
    proxy:
        description: Proxy host and port that Sauce Connect should use to connect to the Sauce Labs cloud.
        required: false
    proxySauce:
        description: Use the proxy configured with -p for the tunnel connection.
        required: false
    region:
        description: Region to connect to (us-west-1, us-east-1, eu-central-1, apac-southeast-1).
        required: true
    sharedTunnel:
        description: Denotes a shared tunnel.
        required: false
    tunnelDomains:
        description: Comma-separated list of domains that you want to tunnel through the Sauce Connect Proxy.
        required: false
    tunnelIdentifier:
        description: Identifier for the tunnel.
        required: false
    tunnelName:
        description: Name for the tunnel.
        required: true
    scVersion:
        description: Version of the saucelabs/sauce-connect docker image.
        required: false
        default: '5.2.2'
    retryTimeout:
        description: Do not retry if this amount of minutes has passed since starting.
        required: false
        default: '2'
outputs:
    sc-pid:
        description: 'PID of the Sauce Connect process'
runs:
    using: 'node20'
    main: 'dist/main/index.js'
    post: 'dist/post/index.js'
