name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "Install Dependencies"
      run: npm install

    - name: "Run Test"
      run: npm test
