name: "PR Checks"
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: "Install Dependencies"
              run: npm install

            - name: "Build the package"
              run: npm run build

            - uses: ./
              with:
                username: ${{ secrets.SAUCE_USERNAME }}
                accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
                tunnelName: github-action-tunnel
                region: 'us-west'
                scVersion: 5.2.2

            - name: "Run Test"
              run: npm run test
              env:
                SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
                SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
