name: "PR Checks"
on: [pull_request, push]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1
            - uses: saucelabs/sauce-connect-action@v0.3.5

            - name: "Install Dependencies"
              run: npm install

            - name: "Run Test"
              run: npm test
