name: "PR Checks"
on: create

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1
            - uses: saucelabs/sauce-connect-action@v0.3.13
              with:
                username: ${{ secrets.SAUCE_USERNAME }}
                accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
                sePort: 4445

            - name: "Install Dependencies"
              run: npm install

            - name: "Run Test"
              run: npm test
